# Generated by Django 5.0.7 on 2024-07-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_contact', models.CharField(max_length=10)),
                ('user_email', models.EmailField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('product_image', models.ImageField(blank=True, default='default_product.jpg', null=True, upload_to='procduct_images/')),
            ],
        ),
    ]
